name: CI - Build and Test (.NET 8)

on:
  pull_request:
    branches: [ develop, staging, main ]

  push:
    branches: [ develop ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    env:
      ASPNETCORE_ENVIRONMENT: Development
      MongoSettings__ConnectionString: ${{ secrets.MONGO_CONNECTION }}
      MongoSettings__Database: ${{ secrets.MONGO_DATABASE_NAME }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity minimal

      - name: Test
        run: dotnet test --no-build --configuration Release --logger "console;verbosity=normal"

      - name: Docker build validation
        run: docker build -t personservice:test -f src/PersonService.Api/Dockerfile .